name: "Build"

on:
  pull_request:
  push:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v11
      - run: nix develop --command make crossbuild_mac --debug
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: binaries-macos
          path: bin/*
          retention-days: 5

  linux-and-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v11
      - run: nix develop --command make crossbuild
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-and-windows
          path: bin/*
          retention-days: 5
